# Generated by Django 2.2.11 on 2020-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200328_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userinfo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
